In [ ]:
import numpy as np
import pandas as pd

#####Create a CSV file for the student’s information with following detail:

#####Data Field Details:

  • Student ID - The Student ID field should be unique and is used to map information and
  data files.
  • First Name - Student's first name
  • Middle Name - Student's middle name
  • Last Name - Student's last name
  • Roll No. - This field is only used if your campus makes a distinction between the
  Student ID and an additional identifier. If you have no Secondary ID for a student,
  simply leave this field blank.
  • Date of Birth - Please use the following format to ensure that age is calculated
  correctly: MM/DD/YYYY.
  • E-mail Address - Preferably official email address
  • Address – Home Address
  • Mobile Number-

#####(Create dataframe and write that to cvs file)

In [ ]:
data = [['1','Harsh','abcd','wxyz','44','11-22-2002','M','guptahs_1@rknec.edu','Nagpur','8635478930',9.05,8.93,95,92,84],
        ['2','Sourav','sbjfv','Sharma','62','11-20-2002','M','sourav@rknec.edu','Nagpur','9783756388',8.82,8.53,85,93,91],
        ['3','Jayesh','Vinay','jlfhd','21','04-04-2002','M','jayesh@rknec.edu','','9483579835',9.52,7.53,98,98,87],
        ['4','Maya','ksajdf','lfjlnf','09','09-10-2002','F','maya@rknec.edu','Nagpur','4985645893',8.82,8.76,95,87,80],
        ['5','Pratik','lsjdfn','oruehi','53','12-22-2001','M','pratik@rknec.edu','Nagpur','4839564958',9.03,9.43,98,82,94],
        ['6','Aastha','gsfgg','khfdvi','22','06-19-2002','F','aastha@rknec.edu','','9835496586',7.95,9.13,79,92,78],
        ['7','Alia','jnvxcb','sbjdir','51','10-21-2002','F','alia@rknec.edu','Nagpur','7839475688',9.23,8.93,92,83,84],
        ['8','Priyanshu','ihsdc','khcv','41','03-10-2000','M','priyanshu@rknec.edu','Nagpur','9864759040',9.10,8.01,88,84,85],
        ['9','Ananya','kshdv','jlhic','29','05-15-2002','F','ananya@rknec.edu','','9846358763',7.53,8.89,85,88,89],
        ['10','Rohan','yufgv','kbjdc','11','01-30-2002','M','rohan@rknec.edu','Nagpur','8458976459',8.53,8.64,90,91,86]]

In [ ]:
df=pd.DataFrame(data,columns=['Student ID','First Name','Middle Name','Last Name','Roll no.','Date of Birth','Gender','E-mail','Address','Mobile no.','SGPA','CGPA','Maths Marks','Physics Marks','Chemistry Marks'])
df

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
0,1,Harsh,Sandesh,Gupta,44,11-22-2002,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84
1,2,Sourav,sbjfv,Sharma,62,11-20-2002,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91
2,3,Jayesh,Vinay,jlfhd,21,04-04-2002,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87
3,4,Maya,ksajdf,lfjlnf,09,09-10-2002,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80
4,5,Pratik,lsjdfn,oruehi,53,12-22-2001,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94
5,6,Aastha,gsfgg,khfdvi,22,06-19-2002,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78
6,7,Alia,jnvxcb,sbjdir,51,10-21-2002,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84
7,8,Priyanshu,ihsdc,khcv,41,03-10-2000,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85
8,9,Ananya,kshdv,jlhic,29,05-15-2002,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89
9,10,Rohan,yufgv,kbjdc,11,01-30-2002,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86

In [ ]:
df.to_csv('D44_data.csv')

1) Print the shape of the data, type of the data and first and last 5 rows.

In [ ]:
df.shape

(10, 15)

In [ ]:
df.dtypes

Student ID          object
First Name          object
Middle Name         object
Last Name           object
Roll no.            object
Date of Birth       object
Gender              object
E-mail              object
Address             object
Mobile no.          object
SGPA               float64
CGPA               float64
Maths Marks          int64
Physics Marks        int64
Chemistry Marks      int64
dtype: object

In [ ]:
df.head(5)

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
0,1,Harsh,Sandesh,Gupta,44,11-22-2002,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84
1,2,Sourav,sbjfv,Sharma,62,11-20-2002,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91
2,3,Jayesh,Vinay,jlfhd,21,04-04-2002,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87
3,4,Maya,ksajdf,lfjlnf,09,09-10-2002,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80
4,5,Pratik,lsjdfn,oruehi,53,12-22-2001,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94

In [ ]:
df.tail(5)

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
5,6,Aastha,gsfgg,khfdvi,22,06-19-2002,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78
6,7,Alia,jnvxcb,sbjdir,51,10-21-2002,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84
7,8,Priyanshu,ihsdc,khcv,41,03-10-2000,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85
8,9,Ananya,kshdv,jlhic,29,05-15-2002,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89
9,10,Rohan,yufgv,kbjdc,11,01-30-2002,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86

2) Replace the abnormal symbols i.e. null value i.e. NaN.

In [ ]:
df.isnull()

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.fillna("Mumbai", inplace=True)
df

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
0,1,Harsh,Sandesh,Gupta,44,11-22-2002,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84
1,2,Sourav,sbjfv,Sharma,62,11-20-2002,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91
2,3,Jayesh,Vinay,jlfhd,21,04-04-2002,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87
3,4,Maya,ksajdf,lfjlnf,09,09-10-2002,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80
4,5,Pratik,lsjdfn,oruehi,53,12-22-2001,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94
5,6,Aastha,gsfgg,khfdvi,22,06-19-2002,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78
6,7,Alia,jnvxcb,sbjdir,51,10-21-2002,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84
7,8,Priyanshu,ihsdc,khcv,41,03-10-2000,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85
8,9,Ananya,kshdv,jlhic,29,05-15-2002,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89
9,10,Rohan,yufgv,kbjdc,11,01-30-2002,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86

3) View basic statistical details like percentile, mean, std deviation, mode, variance, skewness of the data in table & write this in dataset & further create CSV file.

In [ ]:
df2=pd.DataFrame({"Field":['SGPA','CGPA','Maths Marks','Physics Marks','Chemistry Marks'],
                  "Percentile": [df['SGPA'].quantile(q=0.5),df['CGPA'].quantile(q=0.5),df['Maths Marks'].quantile(q=0.5),df['Physics Marks'].quantile(q=0.5),df['Chemistry Marks'].quantile(q=0.5)],
                  "Mean":[df['SGPA'].mean(axis=0),df['CGPA'].mean(axis=0),df['Maths Marks'].mean(axis=0),df['Physics Marks'].mean(axis=0),df['Chemistry Marks'].mean(axis=0)],
                  "Std Deviation":[df['SGPA'].std(axis=0),df['CGPA'].std(axis=0),df['Maths Marks'].std(axis=0),df['Physics Marks'].std(axis=0),df['Chemistry Marks'].std(axis=0)],   
                  "Variance":[df['SGPA'].var(axis=0),df['CGPA'].var(axis=0),df['Maths Marks'].var(axis=0),df['Physics Marks'].var(axis=0),df['Chemistry Marks'].var(axis=0)],
                  "Skewness":[df['SGPA'].skew(axis=0),df['CGPA'].skew(axis=0),df['Maths Marks'].skew(axis=0),df['Physics Marks'].skew(axis=0),df['Chemistry Marks'].skew(axis=0)]
                  })
df2

             Field  Percentile    Mean  Std Deviation   Variance  Skewness
0             SGPA       8.925   8.758       0.605545   0.366684 -1.099675
1             CGPA       8.825   8.678       0.551358   0.303996 -1.039645
2      Maths Marks      91.000  90.500       6.276057  39.388889 -0.471939
3    Physics Marks      89.500  89.000       5.099020  26.000000  0.169716
4  Chemistry Marks      85.500  85.800       4.802777  23.066667  0.055965

In [ ]:
df3=pd.DataFrame({
    "Mode":[df['SGPA'].mode(),df['CGPA'].mode(),df['Maths Marks'].mode(),df['Maths Marks'].mode(),df['Physics Marks'].mode(),df['Chemistry Marks'].mode()]})
df3

                                   Mode
0              0    8.82
dtype: float64
1              0    8.93
dtype: float64
2  0    85
1    95
2    98
dtype: int64
3  0    85
1    95
2    98
dtype: int64
4                  0    92
dtype: int64
5                  0    84
dtype: int64

In [ ]:
df2.to_csv('D44_data2.csv')

4) Drop Student ID column from a given Data frame and print the modified part.

In [ ]:
df.drop(['Student ID'], axis = 1)

,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
0,Harsh,Sandesh,Gupta,44,11-22-2002,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84
1,Sourav,sbjfv,Sharma,62,11-20-2002,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91
2,Jayesh,Vinay,jlfhd,21,04-04-2002,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87
3,Maya,ksajdf,lfjlnf,09,09-10-2002,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80
4,Pratik,lsjdfn,oruehi,53,12-22-2001,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94
5,Aastha,gsfgg,khfdvi,22,06-19-2002,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78
6,Alia,jnvxcb,sbjdir,51,10-21-2002,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84
7,Priyanshu,ihsdc,khcv,41,03-10-2000,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85
8,Ananya,kshdv,jlhic,29,05-15-2002,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89
9,Rohan,yufgv,kbjdc,11,01-30-2002,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86

5) Define a data frame containing month wise data on the basis on Birth month.

In [ ]:
df.sort_values(by='Date of Birth', ascending = True)

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks
9,10,Rohan,yufgv,kbjdc,11,01-30-2002,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86
7,8,Priyanshu,ihsdc,khcv,41,03-10-2000,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85
2,3,Jayesh,Vinay,jlfhd,21,04-04-2002,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87
8,9,Ananya,kshdv,jlhic,29,05-15-2002,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89
5,6,Aastha,gsfgg,khfdvi,22,06-19-2002,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78
3,4,Maya,ksajdf,lfjlnf,09,09-10-2002,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80
6,7,Alia,jnvxcb,sbjdir,51,10-21-2002,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84
1,2,Sourav,sbjfv,Sharma,62,11-20-2002,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91
0,1,Harsh,Sandesh,Gupta,44,11-22-2002,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84
4,5,Pratik,lsjdfn,oruehi,53,12-22-2001,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94

6) Count the number of males, female students

In [ ]:
df['Gender'].value_counts()['M']

6

In [ ]:
df['Gender'].value_counts()['F']

4

7) Calculate the age of all the students from DOB & categorize it in the different age groups (such as between 15-20, 21-25 etc.)

In [ ]:
from datetime import datetime

In [ ]:
df['Date of Birth']=pd.to_datetime(df['Date of Birth'], format="%m-%d-%Y")
df['month_of_birth']=df['Date of Birth'].map(lambda x: x.strftime('%m'))

grouped_df=df.groupby('month_of_birth').size()
grouped_df

month_of_birth
01    1
03    1
04    1
05    1
06    1
09    1
10    1
11    2
12    1
dtype: int64

In [ ]:
now=pd.Timestamp('now')
df['age']=(now-df['Date of Birth']).astype('<m8[Y]')
age_groups = pd.cut(df['age'], bins =[15,20,21,25])
age_intervals=df.groupby(age_groups).size()
age_intervals

age
(15, 20]    9
(20, 21]    0
(21, 25]    1
dtype: int64

8) Extract the domain name from mail address of each student
For ex if input is: abc@rknec.edu then output is: rknec.edu

In [ ]:
lst=[]
for i in range(len(df)):
  t1=df['E-mail'][i].split('@')
  lst.append(t1[1])
lst

['rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu',
 'rknec.edu']

9) Sort the data on the basis of First name.

In [ ]:
df.sort_values(by='First Name', ascending = True)

,Student ID,First Name,Middle Name,Last Name,Roll no.,Date of Birth,Gender,E-mail,Address,Mobile no.,SGPA,CGPA,Maths Marks,Physics Marks,Chemistry Marks,month_of_birth,age
5,6,Aastha,gsfgg,khfdvi,22,2002-06-19,F,aastha@rknec.edu,,9835496586,7.95,9.13,79,92,78,06,19.0
6,7,Alia,jnvxcb,sbjdir,51,2002-10-21,F,alia@rknec.edu,Nagpur,7839475688,9.23,8.93,92,83,84,10,19.0
8,9,Ananya,kshdv,jlhic,29,2002-05-15,F,ananya@rknec.edu,,9846358763,7.53,8.89,85,88,89,05,19.0
0,1,Harsh,Sandesh,Gupta,44,2002-11-22,M,guptahs_1@rknec.edu,Nagpur,8635478930,9.05,8.93,95,92,84,11,19.0
2,3,Jayesh,Vinay,jlfhd,21,2002-04-04,M,jayesh@rknec.edu,,9483579835,9.52,7.53,98,98,87,04,20.0
3,4,Maya,ksajdf,lfjlnf,09,2002-09-10,F,maya@rknec.edu,Nagpur,4985645893,8.82,8.76,95,87,80,09,19.0
4,5,Pratik,lsjdfn,oruehi,53,2001-12-22,M,pratik@rknec.edu,Nagpur,4839564958,9.03,9.43,98,82,94,12,20.0
7,8,Priyanshu,ihsdc,khcv,41,2000-03-10,M,priyanshu@rknec.edu,Nagpur,9864759040,9.10,8.01,88,84,85,03,22.0
9,10,Rohan,yufgv,kbjdc,11,2002-01-30,M,rohan@rknec.edu,Nagpur,8458976459,8.53,8.64,90,91,86,01,20.0
1,2,Sourav,sbjfv,Sharma,62,2002-11-20,M,sourav@rknec.edu,Nagpur,9783756388,8.82,8.53,85,93,91,11,19.0

10) How many local students are there (from Nagpur)

In [ ]:
x=0
for i in df['Address']:
  if i == 'Nagpur':
    x=x+1
print(x)

7